-- public.assignment_status definition

-- Drop table

-- DROP TABLE assignment_status;
CREATE TABLE assignment_status (
	id_status NUMBER GENERATED BY DEFAULT AS IDENTITY,
	status_code varchar2(255) NOT NULL UNIQUE,
	status_name varchar2(255) NOT NULL,
	PRIMARY KEY (id_status)
);

-- public.assignments definition

-- Drop table

-- DROP TABLE assignments;
CREATE TABLE assignments (
	id_assignment NUMBER GENERATED BY DEFAULT AS IDENTITY,
	ref_id_form NUMBER NOT NULL,
	ref_id_team_member NUMBER NOT NULL,
	created_at timestamp NULL,
	created_by varchar2(255) NULL,
	updated_at timestamp NULL,
	updated_by VARCHAR2(255) NULL,
	ref_id_status NUMBER NULL,
	name varchar2(255) NULL,
	phone varchar2(50) NULL,
	message varchar2(255) NULL,
	assignment_ref VARCHAR2(255) NOT NULL,
	final_score NUMBER DEFAULT 0,
	PRIMARY KEY (id_assignment)
);

-- public.form definition

-- Drop table

-- DROP TABLE form;
CREATE TABLE form (
	id_form NUMBER GENERATED BY DEFAULT AS IDENTITY,
	form_name varchar2(255) NULL,
	form_is_active VARCHAR(1) DEFAULT ('Y'),
	created_at timestamp NULL,
	created_by varchar2(255) NULL,
	updated_by varchar2(255) NULL,
	updated_at timestamp NULL,
	PRIMARY KEY (id_form)
);

-- public.question definition

-- Drop table

-- DROP TABLE question;
CREATE TABLE question (
	id_question NUMBER GENERATED BY DEFAULT AS IDENTITY,
	ref_id_form NUMBER NOT NULL,
	question_details VARCHAR2(255) NULL,
	question_order NUMBER NULL,
	ref_id_question_type NUMBER NULL,
	created_at timestamp NULL,
	created_by varchar2(255) NULL,
	updated_at timestamp NULL,
	updated_by VARCHAR2(255) NULL,
	is_active VARCHAR2(1) DEFAULT ('Y'),
	PRIMARY KEY (id_question)
);

-- DROP TABLE question_type;
CREATE TABLE question_type (
	id_question_type NUMBER GENERATED BY DEFAULT AS IDENTITY,
	question_type_code varchar2(255) NULL UNIQUE,
	question_type_name varchar2(255) NULL,
	PRIMARY KEY (id_question_type)
);

-- public.team_department definition

-- Drop table

-- DROP TABLE team_department;

CREATE TABLE team_department (
	id_team_department NUMBER GENERATED BY DEFAULT AS IDENTITY,
	department_name varchar2(255) NULL,
	department_description varchar2(255) NULL
);
-- public.team_member definition

-- Drop table

-- DROP TABLE team_member;

CREATE TABLE team_member (
	id_team_member NUMBER GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar2(255) NULL,
	last_name varchar2(255) NULL,
	contact varchar2(255) NULL UNIQUE,
	email varchar2(255) NULL UNIQUE,
	created_at timestamp NULL,
	created_by varchar2(255) NULL,
	updated_at timestamp NULL,
	updated_by varchar2(255) NULL,
	username varchar2(255) NULL UNIQUE,
	password varchar2(255) NULL,
	ref_id_department NUMBER NULL,
	is_active varchar2 (1) DEFAULT ('Y'),
	PRIMARY KEY (id_team_member)
);

ALTER TABLE ASSIGNMENTS modify (FINAL_SCORE decimal(2, 20));